[2025-04-13T22:13:22.437+0000] {processor.py:186} INFO - Started process (PID=85) to work on /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:13:22.438+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/custom_dag_improved.py for tasks to queue
[2025-04-13T22:13:22.443+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:13:22.442+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:13:22.448+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:13:22.446+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/custom_dag_improved.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/custom_dag_improved.py", line 29
    logging.info(f"Data from {file.name}:
                 ^
SyntaxError: unterminated f-string literal (detected at line 29)
[2025-04-13T22:13:22.450+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:13:22.485+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/custom_dag_improved.py took 0.059 seconds
[2025-04-13T22:13:53.449+0000] {processor.py:186} INFO - Started process (PID=98) to work on /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:13:53.451+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/custom_dag_improved.py for tasks to queue
[2025-04-13T22:13:53.453+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:13:53.453+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:13:53.458+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:13:53.456+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/custom_dag_improved.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/custom_dag_improved.py", line 29
    logging.info(f"Data from {file.name}:
                 ^
SyntaxError: unterminated f-string literal (detected at line 29)
[2025-04-13T22:13:53.458+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:13:53.482+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/custom_dag_improved.py took 0.040 seconds
[2025-04-13T22:14:23.545+0000] {processor.py:186} INFO - Started process (PID=108) to work on /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:14:23.547+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/custom_dag_improved.py for tasks to queue
[2025-04-13T22:14:23.550+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:14:23.550+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:14:23.555+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:14:23.553+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/custom_dag_improved.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/custom_dag_improved.py", line 29
    logging.info(f"Data from {file.name}:
                 ^
SyntaxError: unterminated f-string literal (detected at line 29)
[2025-04-13T22:14:23.556+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:14:23.583+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/custom_dag_improved.py took 0.047 seconds
[2025-04-13T22:14:54.119+0000] {processor.py:186} INFO - Started process (PID=120) to work on /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:14:54.130+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/custom_dag_improved.py for tasks to queue
[2025-04-13T22:14:54.135+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:14:54.134+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:14:54.142+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:14:54.139+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/custom_dag_improved.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/custom_dag_improved.py", line 29
    logging.info(f"Data from {file.name}:
                 ^
SyntaxError: unterminated f-string literal (detected at line 29)
[2025-04-13T22:14:54.143+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:14:54.209+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/custom_dag_improved.py took 0.105 seconds
[2025-04-13T22:15:24.621+0000] {processor.py:186} INFO - Started process (PID=134) to work on /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:15:24.633+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/custom_dag_improved.py for tasks to queue
[2025-04-13T22:15:24.637+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:15:24.637+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:15:24.651+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:15:24.642+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/custom_dag_improved.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/custom_dag_improved.py", line 29
    logging.info(f"Data from {file.name}:
                 ^
SyntaxError: unterminated f-string literal (detected at line 29)
[2025-04-13T22:15:24.653+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:15:24.702+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/custom_dag_improved.py took 0.114 seconds
[2025-04-13T22:15:55.379+0000] {processor.py:186} INFO - Started process (PID=147) to work on /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:15:55.380+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/custom_dag_improved.py for tasks to queue
[2025-04-13T22:15:55.383+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:15:55.382+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:15:55.387+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:15:55.386+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/custom_dag_improved.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/custom_dag_improved.py", line 29
    logging.info(f"Data from {file.name}:
                 ^
SyntaxError: unterminated f-string literal (detected at line 29)
[2025-04-13T22:15:55.388+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:15:55.413+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/custom_dag_improved.py took 0.043 seconds
[2025-04-13T22:16:26.159+0000] {processor.py:186} INFO - Started process (PID=160) to work on /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:16:26.167+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/custom_dag_improved.py for tasks to queue
[2025-04-13T22:16:26.169+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:16:26.169+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:16:26.173+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:16:26.172+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/custom_dag_improved.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/custom_dag_improved.py", line 29
    logging.info(f"Data from {file.name}:
                 ^
SyntaxError: unterminated f-string literal (detected at line 29)
[2025-04-13T22:16:26.173+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:16:26.195+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/custom_dag_improved.py took 0.043 seconds
[2025-04-13T22:16:56.381+0000] {processor.py:186} INFO - Started process (PID=173) to work on /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:16:56.390+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/custom_dag_improved.py for tasks to queue
[2025-04-13T22:16:56.395+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:16:56.395+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:16:56.401+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:16:56.399+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/custom_dag_improved.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/custom_dag_improved.py", line 29
    logging.info(f"Data from {file.name}:
                 ^
SyntaxError: unterminated f-string literal (detected at line 29)
[2025-04-13T22:16:56.402+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:16:56.422+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/custom_dag_improved.py took 0.055 seconds
[2025-04-13T22:17:27.044+0000] {processor.py:186} INFO - Started process (PID=187) to work on /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:17:27.052+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/custom_dag_improved.py for tasks to queue
[2025-04-13T22:17:27.055+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:17:27.055+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:17:27.059+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:17:27.058+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/custom_dag_improved.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/custom_dag_improved.py", line 29
    logging.info(f"Data from {file.name}:
                 ^
SyntaxError: unterminated f-string literal (detected at line 29)
[2025-04-13T22:17:27.060+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:17:27.080+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/custom_dag_improved.py took 0.044 seconds
[2025-04-13T22:17:57.611+0000] {processor.py:186} INFO - Started process (PID=201) to work on /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:17:57.620+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/custom_dag_improved.py for tasks to queue
[2025-04-13T22:17:57.623+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:17:57.623+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:17:57.628+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:17:57.627+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/custom_dag_improved.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/custom_dag_improved.py", line 29
    logging.info(f"Data from {file.name}:
                 ^
SyntaxError: unterminated f-string literal (detected at line 29)
[2025-04-13T22:17:57.629+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:17:57.653+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/custom_dag_improved.py took 0.049 seconds
[2025-04-13T22:18:27.795+0000] {processor.py:186} INFO - Started process (PID=214) to work on /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:18:27.804+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/custom_dag_improved.py for tasks to queue
[2025-04-13T22:18:27.807+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:18:27.807+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:18:27.810+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:18:27.809+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/custom_dag_improved.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/custom_dag_improved.py", line 29
    logging.info(f"Data from {file.name}:
                 ^
SyntaxError: unterminated f-string literal (detected at line 29)
[2025-04-13T22:18:27.811+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:18:27.831+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/custom_dag_improved.py took 0.042 seconds
[2025-04-13T22:18:58.006+0000] {processor.py:186} INFO - Started process (PID=227) to work on /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:18:58.016+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/custom_dag_improved.py for tasks to queue
[2025-04-13T22:18:58.024+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:18:58.023+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:18:58.032+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:18:58.029+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/custom_dag_improved.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/custom_dag_improved.py", line 29
    logging.info(f"Data from {file.name}:
                 ^
SyntaxError: unterminated f-string literal (detected at line 29)
[2025-04-13T22:18:58.033+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:18:58.055+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/custom_dag_improved.py took 0.064 seconds
[2025-04-13T22:19:28.410+0000] {processor.py:186} INFO - Started process (PID=240) to work on /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:19:28.418+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/custom_dag_improved.py for tasks to queue
[2025-04-13T22:19:28.421+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:19:28.421+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:19:28.425+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:19:28.424+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/custom_dag_improved.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/custom_dag_improved.py", line 29
    logging.info(f"Data from {file.name}:
                 ^
SyntaxError: unterminated f-string literal (detected at line 29)
[2025-04-13T22:19:28.426+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:19:28.446+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/custom_dag_improved.py took 0.043 seconds
[2025-04-13T22:19:58.710+0000] {processor.py:186} INFO - Started process (PID=253) to work on /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:19:58.719+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/custom_dag_improved.py for tasks to queue
[2025-04-13T22:19:58.722+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:19:58.722+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:19:58.728+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:19:58.726+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/custom_dag_improved.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/custom_dag_improved.py", line 29
    logging.info(f"Data from {file.name}:
                 ^
SyntaxError: unterminated f-string literal (detected at line 29)
[2025-04-13T22:19:58.729+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:19:58.759+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/custom_dag_improved.py took 0.059 seconds
[2025-04-13T22:20:29.551+0000] {processor.py:186} INFO - Started process (PID=266) to work on /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:20:29.560+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/custom_dag_improved.py for tasks to queue
[2025-04-13T22:20:29.566+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:20:29.563+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:20:29.576+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:20:29.574+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/custom_dag_improved.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/custom_dag_improved.py", line 29
    logging.info(f"Data from {file.name}:
                 ^
SyntaxError: unterminated f-string literal (detected at line 29)
[2025-04-13T22:20:29.580+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:20:29.626+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/custom_dag_improved.py took 0.086 seconds
[2025-04-13T22:21:00.137+0000] {processor.py:186} INFO - Started process (PID=279) to work on /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:21:00.148+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/custom_dag_improved.py for tasks to queue
[2025-04-13T22:21:00.152+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:21:00.152+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:21:00.165+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:21:00.162+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/custom_dag_improved.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/custom_dag_improved.py", line 29
    logging.info(f"Data from {file.name}:
                 ^
SyntaxError: unterminated f-string literal (detected at line 29)
[2025-04-13T22:21:00.167+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:21:00.218+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/custom_dag_improved.py took 0.095 seconds
[2025-04-13T22:21:30.394+0000] {processor.py:186} INFO - Started process (PID=292) to work on /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:21:30.403+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/custom_dag_improved.py for tasks to queue
[2025-04-13T22:21:30.406+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:21:30.406+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:21:30.411+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:21:30.409+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/custom_dag_improved.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/custom_dag_improved.py", line 29
    logging.info(f"Data from {file.name}:
                 ^
SyntaxError: unterminated f-string literal (detected at line 29)
[2025-04-13T22:21:30.412+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:21:30.439+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/custom_dag_improved.py took 0.051 seconds
[2025-04-13T22:22:00.626+0000] {processor.py:186} INFO - Started process (PID=305) to work on /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:22:00.635+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/custom_dag_improved.py for tasks to queue
[2025-04-13T22:22:00.638+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:22:00.638+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:22:00.643+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:22:00.642+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/custom_dag_improved.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/custom_dag_improved.py", line 29
    logging.info(f"Data from {file.name}:
                 ^
SyntaxError: unterminated f-string literal (detected at line 29)
[2025-04-13T22:22:00.644+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:22:00.671+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/custom_dag_improved.py took 0.058 seconds
[2025-04-13T22:22:30.943+0000] {processor.py:186} INFO - Started process (PID=318) to work on /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:22:30.952+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/custom_dag_improved.py for tasks to queue
[2025-04-13T22:22:30.958+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:22:30.957+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:22:30.967+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:22:30.965+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/custom_dag_improved.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/custom_dag_improved.py", line 29
    logging.info(f"Data from {file.name}:
                 ^
SyntaxError: unterminated f-string literal (detected at line 29)
[2025-04-13T22:22:30.969+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:22:30.996+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/custom_dag_improved.py took 0.082 seconds
[2025-04-13T22:23:01.067+0000] {processor.py:186} INFO - Started process (PID=332) to work on /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:23:01.076+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/custom_dag_improved.py for tasks to queue
[2025-04-13T22:23:01.078+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:23:01.078+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:23:01.082+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:23:01.081+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/custom_dag_improved.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/custom_dag_improved.py", line 29
    logging.info(f"Data from {file.name}:
                 ^
SyntaxError: unterminated f-string literal (detected at line 29)
[2025-04-13T22:23:01.082+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:23:01.106+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/custom_dag_improved.py took 0.048 seconds
[2025-04-13T22:23:31.362+0000] {processor.py:186} INFO - Started process (PID=345) to work on /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:23:31.370+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/custom_dag_improved.py for tasks to queue
[2025-04-13T22:23:31.373+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:23:31.372+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:23:31.377+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:23:31.375+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/custom_dag_improved.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/custom_dag_improved.py", line 29
    logging.info(f"Data from {file.name}:
                 ^
SyntaxError: unterminated f-string literal (detected at line 29)
[2025-04-13T22:23:31.377+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:23:31.398+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/custom_dag_improved.py took 0.043 seconds
[2025-04-13T22:24:01.728+0000] {processor.py:186} INFO - Started process (PID=359) to work on /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:24:01.730+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/custom_dag_improved.py for tasks to queue
[2025-04-13T22:24:01.735+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:24:01.735+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:24:01.742+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:24:01.740+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/custom_dag_improved.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/custom_dag_improved.py", line 29
    logging.info(f"Data from {file.name}:
                 ^
SyntaxError: unterminated f-string literal (detected at line 29)
[2025-04-13T22:24:01.742+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:24:01.777+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/custom_dag_improved.py took 0.063 seconds
[2025-04-13T22:24:31.979+0000] {processor.py:186} INFO - Started process (PID=372) to work on /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:24:31.992+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/custom_dag_improved.py for tasks to queue
[2025-04-13T22:24:31.997+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:24:31.996+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:24:32.004+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:24:32.002+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/custom_dag_improved.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/custom_dag_improved.py", line 29
    logging.info(f"Data from {file.name}:
                 ^
SyntaxError: unterminated f-string literal (detected at line 29)
[2025-04-13T22:24:32.014+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:24:32.075+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/custom_dag_improved.py took 0.124 seconds
[2025-04-13T22:25:02.176+0000] {processor.py:186} INFO - Started process (PID=385) to work on /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:25:02.185+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/custom_dag_improved.py for tasks to queue
[2025-04-13T22:25:02.191+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:25:02.190+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:25:02.197+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:25:02.195+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/custom_dag_improved.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/custom_dag_improved.py", line 29
    logging.info(f"Data from {file.name}:
                 ^
SyntaxError: unterminated f-string literal (detected at line 29)
[2025-04-13T22:25:02.198+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:25:02.220+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/custom_dag_improved.py took 0.064 seconds
[2025-04-13T22:25:32.353+0000] {processor.py:186} INFO - Started process (PID=399) to work on /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:25:32.362+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/custom_dag_improved.py for tasks to queue
[2025-04-13T22:25:32.367+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:25:32.366+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:25:32.372+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:25:32.370+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/custom_dag_improved.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/custom_dag_improved.py", line 29
    logging.info(f"Data from {file.name}:
                 ^
SyntaxError: unterminated f-string literal (detected at line 29)
[2025-04-13T22:25:32.373+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:25:32.396+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/custom_dag_improved.py took 0.052 seconds
[2025-04-13T22:26:02.825+0000] {processor.py:186} INFO - Started process (PID=412) to work on /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:26:02.834+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/custom_dag_improved.py for tasks to queue
[2025-04-13T22:26:02.838+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:26:02.837+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:26:02.843+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:26:02.841+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/custom_dag_improved.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/custom_dag_improved.py", line 29
    logging.info(f"Data from {file.name}:
                 ^
SyntaxError: unterminated f-string literal (detected at line 29)
[2025-04-13T22:26:02.844+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:26:02.875+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/custom_dag_improved.py took 0.059 seconds
[2025-04-13T22:26:33.141+0000] {processor.py:186} INFO - Started process (PID=425) to work on /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:26:33.149+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/custom_dag_improved.py for tasks to queue
[2025-04-13T22:26:33.154+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:26:33.153+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:26:33.165+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:26:33.163+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/custom_dag_improved.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/custom_dag_improved.py", line 29
    logging.info(f"Data from {file.name}:
                 ^
SyntaxError: unterminated f-string literal (detected at line 29)
[2025-04-13T22:26:33.166+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:26:33.196+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/custom_dag_improved.py took 0.062 seconds
[2025-04-13T22:27:03.590+0000] {processor.py:186} INFO - Started process (PID=438) to work on /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:27:03.593+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/custom_dag_improved.py for tasks to queue
[2025-04-13T22:27:03.596+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:27:03.596+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:27:03.603+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:27:03.600+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/custom_dag_improved.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/custom_dag_improved.py", line 29
    logging.info(f"Data from {file.name}:
                 ^
SyntaxError: unterminated f-string literal (detected at line 29)
[2025-04-13T22:27:03.604+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:27:03.627+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/custom_dag_improved.py took 0.049 seconds
[2025-04-13T22:27:33.869+0000] {processor.py:186} INFO - Started process (PID=451) to work on /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:27:33.878+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/custom_dag_improved.py for tasks to queue
[2025-04-13T22:27:33.883+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:27:33.882+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:27:33.891+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:27:33.889+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/custom_dag_improved.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/custom_dag_improved.py", line 29
    logging.info(f"Data from {file.name}:
                 ^
SyntaxError: unterminated f-string literal (detected at line 29)
[2025-04-13T22:27:33.893+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:27:33.930+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/custom_dag_improved.py took 0.079 seconds
[2025-04-13T22:28:03.975+0000] {processor.py:186} INFO - Started process (PID=464) to work on /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:28:03.984+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/custom_dag_improved.py for tasks to queue
[2025-04-13T22:28:03.997+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:28:03.997+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:28:04.007+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:28:04.005+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/custom_dag_improved.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/custom_dag_improved.py", line 29
    logging.info(f"Data from {file.name}:
                 ^
SyntaxError: unterminated f-string literal (detected at line 29)
[2025-04-13T22:28:04.008+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:28:04.036+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/custom_dag_improved.py took 0.072 seconds
[2025-04-13T22:28:34.149+0000] {processor.py:186} INFO - Started process (PID=478) to work on /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:28:34.150+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/custom_dag_improved.py for tasks to queue
[2025-04-13T22:28:34.153+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:28:34.153+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:28:34.158+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:28:34.157+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/custom_dag_improved.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/custom_dag_improved.py", line 29
    logging.info(f"Data from {file.name}:
                 ^
SyntaxError: unterminated f-string literal (detected at line 29)
[2025-04-13T22:28:34.159+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:28:34.211+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/custom_dag_improved.py took 0.072 seconds
[2025-04-13T22:29:04.424+0000] {processor.py:186} INFO - Started process (PID=491) to work on /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:29:04.432+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/custom_dag_improved.py for tasks to queue
[2025-04-13T22:29:04.435+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:29:04.435+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:29:04.439+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:29:04.438+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/custom_dag_improved.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/custom_dag_improved.py", line 29
    logging.info(f"Data from {file.name}:
                 ^
SyntaxError: unterminated f-string literal (detected at line 29)
[2025-04-13T22:29:04.440+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:29:04.466+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/custom_dag_improved.py took 0.051 seconds
[2025-04-13T22:29:35.247+0000] {processor.py:186} INFO - Started process (PID=504) to work on /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:29:35.248+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/custom_dag_improved.py for tasks to queue
[2025-04-13T22:29:35.252+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:29:35.251+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:29:35.258+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:29:35.256+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/custom_dag_improved.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/custom_dag_improved.py", line 29
    logging.info(f"Data from {file.name}:
                 ^
SyntaxError: unterminated f-string literal (detected at line 29)
[2025-04-13T22:29:35.259+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:29:35.291+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/custom_dag_improved.py took 0.056 seconds
[2025-04-13T22:30:05.945+0000] {processor.py:186} INFO - Started process (PID=517) to work on /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:30:05.954+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/custom_dag_improved.py for tasks to queue
[2025-04-13T22:30:05.956+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:30:05.956+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:30:05.960+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:30:05.959+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/custom_dag_improved.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/custom_dag_improved.py", line 29
    logging.info(f"Data from {file.name}:
                 ^
SyntaxError: unterminated f-string literal (detected at line 29)
[2025-04-13T22:30:05.960+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:30:05.979+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/custom_dag_improved.py took 0.050 seconds
[2025-04-13T22:30:36.624+0000] {processor.py:186} INFO - Started process (PID=531) to work on /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:30:36.634+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/custom_dag_improved.py for tasks to queue
[2025-04-13T22:30:36.639+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:30:36.638+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:30:36.646+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:30:36.644+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/custom_dag_improved.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/custom_dag_improved.py", line 29
    logging.info(f"Data from {file.name}:
                 ^
SyntaxError: unterminated f-string literal (detected at line 29)
[2025-04-13T22:30:36.648+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:30:36.672+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/custom_dag_improved.py took 0.063 seconds
[2025-04-13T22:31:06.889+0000] {processor.py:186} INFO - Started process (PID=542) to work on /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:31:06.891+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/custom_dag_improved.py for tasks to queue
[2025-04-13T22:31:06.895+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:31:06.895+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:31:06.905+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:31:06.902+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/custom_dag_improved.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/custom_dag_improved.py", line 29
    logging.info(f"Data from {file.name}:
                 ^
SyntaxError: unterminated f-string literal (detected at line 29)
[2025-04-13T22:31:06.906+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:31:06.939+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/custom_dag_improved.py took 0.065 seconds
[2025-04-13T22:31:37.914+0000] {processor.py:186} INFO - Started process (PID=556) to work on /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:31:37.915+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/custom_dag_improved.py for tasks to queue
[2025-04-13T22:31:37.918+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:31:37.917+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:31:37.922+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:31:37.920+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/custom_dag_improved.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/custom_dag_improved.py", line 29
    logging.info(f"Data from {file.name}:
                 ^
SyntaxError: unterminated f-string literal (detected at line 29)
[2025-04-13T22:31:37.923+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:31:37.948+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/custom_dag_improved.py took 0.041 seconds
[2025-04-13T22:32:08.866+0000] {processor.py:186} INFO - Started process (PID=569) to work on /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:32:08.867+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/custom_dag_improved.py for tasks to queue
[2025-04-13T22:32:08.870+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:32:08.869+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:32:08.875+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:32:08.873+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/custom_dag_improved.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/custom_dag_improved.py", line 29
    logging.info(f"Data from {file.name}:
                 ^
SyntaxError: unterminated f-string literal (detected at line 29)
[2025-04-13T22:32:08.876+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:32:08.900+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/custom_dag_improved.py took 0.043 seconds
[2025-04-13T22:32:40.024+0000] {processor.py:186} INFO - Started process (PID=589) to work on /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:32:40.026+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/custom_dag_improved.py for tasks to queue
[2025-04-13T22:32:40.031+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:32:40.029+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:32:40.038+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:32:40.036+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/custom_dag_improved.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/custom_dag_improved.py", line 29
    logging.info(f"Data from {file.name}:
                 ^
SyntaxError: unterminated f-string literal (detected at line 29)
[2025-04-13T22:32:40.040+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:32:40.077+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/custom_dag_improved.py took 0.067 seconds
[2025-04-13T22:33:11.097+0000] {processor.py:186} INFO - Started process (PID=602) to work on /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:33:11.098+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/custom_dag_improved.py for tasks to queue
[2025-04-13T22:33:11.101+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:33:11.100+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:33:11.105+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:33:11.104+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/custom_dag_improved.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/custom_dag_improved.py", line 29
    logging.info(f"Data from {file.name}:
                 ^
SyntaxError: unterminated f-string literal (detected at line 29)
[2025-04-13T22:33:11.106+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:33:11.133+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/custom_dag_improved.py took 0.044 seconds
[2025-04-13T22:33:42.710+0000] {processor.py:186} INFO - Started process (PID=615) to work on /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:33:42.711+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/custom_dag_improved.py for tasks to queue
[2025-04-13T22:33:42.714+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:33:42.714+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:33:42.720+0000] {logging_mixin.py:190} INFO - [2025-04-13T22:33:42.718+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/custom_dag_improved.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/custom_dag_improved.py", line 29
    logging.info(f"Data from {file.name}:
                 ^
SyntaxError: unterminated f-string literal (detected at line 29)
[2025-04-13T22:33:42.721+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_dag_improved.py
[2025-04-13T22:33:42.744+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/custom_dag_improved.py took 0.047 seconds
